### ISSUE TITLE
Previous/next card id on printings

### ISSUE THREAD

**Issue by distributive** [NetrunnerDB/netrunnerdb-api-server#171]
It could be beneficial to have printings output the id of their neighbours. e.g.
```js
data: {
  id: "00012"
  attributes: {
    ...
    next_printing_id: "00013",
    previous_printing_id: "00011"
  }
}
```
(There's probably some clearer names we could give them)

**Comment by plural** [comment]
position and position_in_set help with this somewhat.

This feels like a UI concern creeping into the API, but let's keep the issue open so we can look at it a bit down the road.

**Comment by plural** [comment]
We won't be handling this in the API.  Position allows this to be done by applications, but it is fundamentally a UI concern.
