### ISSUE TITLE
Restriction `points` and `universal_faction_cost` suggestion

### ISSUE THREAD

**Issue by North101** [NetrunnerDB/netrunnerdb-api-server#199]
The API is looking great. I was looking through the API for restrictions and I think its a little weird to have `points` and `universal_faction_costs` represented as:
```json
{
  "points": {
    "1": [
      "24_7_news_cycle"
    ]
  }
}
```

instead of
```json
{
  "points": {
    "24_7_news_cycle": 1
  }
}
```

On the client side you'd need to convert the value to an int and it seems unnecessary

**Comment by plural** [comment]
Deployed!  Thank you for this contribution.
