### ISSUE TITLE
Suggestions: remove `card_` prefix

### ISSUE THREAD

**Issue by North101** [NetrunnerDB/netrunnerdb-api-server#204]
I think it would be cleaner to drop the `card_` prefix. It feels unnecessary. 

* `card_cycle` -> `cycle`
* `card_pool` -> `pool`
* `card_pool_card_set` -> `pool_set`
* `card_set_type` -> `set_type`
* `card_set` -> `set`
* `card_subtype` -> `subtype`
* `card_type` -> `type`
* `card_card_subtype` -> `card_subtype`

**Comment by NoahTheDuke** [comment]
I believe this is partly because Ruby has built-in methods and objects that share names with those words.
