### ISSUE TITLE
Rename cards in decklist resource

### ISSUE THREAD

**Issue by distributive** [NetrunnerDB/netrunnerdb-api-server#254]
In the decklist model, `cards` is a computed attribute with the same name as the `cards` relationship.

Please change the name of the computed attribute to `cardsCounts`

**Comment by plural** [comment]
how about card_slots instead?

**Comment by plural** [comment]
how about card_slots instead?

**Comment by plural** [comment]
@distributive - what do you think about card_slots as a rpelacement name?

**Comment by distributive** [comment]
Honestly I don't care what they're called as long as it isn't `cards`

**Comment by plural** [comment]
The deck (private) and decklist (public) resources have "card_slots" now in place of cards.

Prod hasn't been updated with this, but i'll update api-preview tomorrow.
