### ISSUE TITLE
Using kebab case for URLs and fields

### ISSUE THREAD

**Issue by locks** [NetrunnerDB/netrunnerdb-api-server#59]
The implicit default for JSON:API is to use kebab-case for identifiers, so the endpoint for card cycles would be `/api/v3/public/card-cycles`. Same for fields, it would be `card-cycle-id` in the payload.
How do we feel about changing the API to use that convention?

**Comment by plural** [comment]
heheh.  i changed it to _ to match the json file names, our general preference for underscores over dashes.  What are the benefits on the JS side for having the kebab case over underscores in the api end points?

I don't know if it is a useful thing with a benefit or a style thing.

**Comment by plural** [comment]
it looks like a quick change in the adapter for the api has dealt with this issue.  @locks - do you feel strongly about this?

**Comment by locks** [comment]
I have a slight preference for doing it server-side because then it's one fewer step when deserializing things in the front-end and some requests might notice a tiny improvement. That said, let's worry about other things!
